-- CreateTable
CREATE TABLE `ihNum` (
    `ihn_id` INTEGER NOT NULL AUTO_INCREMENT,
    `ihn_createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ihn_num` INTEGER NOT NULL DEFAULT 0,

    PRIMARY KEY (`ihn_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
